sudo: none

language: java

notifications:
  email: false

jdk:
- openjdk8

script:
    - ./gradlew build --scan -s
#- test/run.sh
  #s- mvn --version
  # Skip unit test in CI
  #- mvn clean install -Dmaven.test.skip=true